//! DBML (Database Markup Language) import/export.
//!
//! DBML is the interchange format used by [dbdiagram.io](https://dbdiagram.io)
//! and is widely supported by mainstream ER tooling.

use crate::error::{Error, Result};
use crate::model::{Attribute, Cardinality, Diagram, DiagramMetadata, Relationship};
use uuid::Uuid;

/// Export a diagram to DBML text.
pub fn export_dbml(diagram: &Diagram) -> String {
    let mut out = String::new();
    out.push_str(&format!("// Generated by er-core {}\n", crate::VERSION));
    if !diagram.name.is_empty() {
        out.push_str(&format!("// Project: {}\n", diagram.name));
    }
    out.push('\n');

    for entity in &diagram.entities {
        out.push_str(&format!(
            "Table {} {{\n",
            quote_ident_if_needed(&entity.name)
        ));
        for attr in &entity.attributes {
            out.push_str(&format!(
                "  {} {}",
                quote_ident_if_needed(&attr.name),
                map_type(&attr.data_type)
            ));
            let mut settings = Vec::new();
            if attr.is_pk {
                settings.push("pk".to_string());
            }
            if attr.is_unique && !attr.is_pk {
                settings.push("unique".to_string());
            }
            if !attr.is_nullable {
                settings.push("not null".to_string());
            }
            if attr.is_fk {
                // FK is expressed via Ref; still mark note for clarity.
                settings.push("note: 'FK'".to_string());
            }
            if let Some(note) = &attr.note {
                settings.push(format!("note: '{}'", escape_note(note)));
            }
            if !settings.is_empty() {
                out.push_str(&format!(" [{}]", settings.join(", ")));
            }
            out.push('\n');
        }
        if let Some(note) = &entity.note {
            out.push_str(&format!("  Note: '{}'\n", escape_note(note)));
        }
        out.push_str("}\n\n");
    }

    for rel in &diagram.relationships {
        let from_fields = if rel.from_fields.is_empty() {
            guess_pk_fields(diagram, &rel.from_entity)
        } else {
            rel.from_fields.clone()
        };
        let to_fields = if rel.to_fields.is_empty() {
            guess_fk_fields(diagram, &rel.to_entity, &rel.from_entity)
        } else {
            rel.to_fields.clone()
        };

        // Prefer many-side as the FK holder when cardinality suggests it.
        let (left_table, left_fields, right_table, right_fields, op) =
            dbml_ref_sides(rel, &from_fields, &to_fields);

        let left = format!(
            "{}.{}",
            quote_ident_if_needed(&left_table),
            format_field_list(&left_fields)
        );
        let right = format!(
            "{}.{}",
            quote_ident_if_needed(&right_table),
            format_field_list(&right_fields)
        );

        if let Some(label) = &rel.label {
            out.push_str(&format!("// {}\n", label));
        }
        out.push_str(&format!("Ref: {left} {op} {right}\n"));
    }

    out
}

/// Import a DBML document into a [`Diagram`].
pub fn import_dbml(input: &str) -> Result<Diagram> {
    let mut diagram = Diagram::new("Imported DBML");
    diagram.metadata = Some(DiagramMetadata {
        source: Some("dbml".into()),
        notes: None,
    });

    let mut lines = input.lines().enumerate().peekable();
    let mut current_table: Option<String> = None;

    while let Some((idx, raw)) = lines.next() {
        let line_no = idx + 1;
        let line = strip_dbml_comment(raw).trim();
        if line.is_empty() {
            continue;
        }

        let lower = line.to_ascii_lowercase();

        if lower.starts_with("project ") {
            // Project name { ... }  or Project name
            let rest = line[7..].trim();
            let name = rest
                .split_whitespace()
                .next()
                .unwrap_or("Imported DBML")
                .trim_matches('{')
                .trim()
                .to_string();
            if !name.is_empty() {
                diagram.name = unquote(&name).to_string();
            }
            if rest.contains('{') && !rest.contains('}') {
                // skip project block
                for (_, raw) in lines.by_ref() {
                    if raw.trim().starts_with('}') {
                        break;
                    }
                }
            }
            continue;
        }

        if lower.starts_with("table ") {
            let rest = line[5..].trim();
            let name_part = rest.split('{').next().unwrap_or(rest).trim();
            // Ignore "as alias"
            let name = name_part
                .split_whitespace()
                .take_while(|t| !t.eq_ignore_ascii_case("as"))
                .collect::<Vec<_>>()
                .join(" ");
            let name = unquote(name.trim()).to_string();
            if name.is_empty() {
                return Err(Error::parse(line_no, "table name missing"));
            }
            diagram.ensure_entity(&name);
            current_table = Some(name);
            if line.contains('}') && line.matches('{').count() == line.matches('}').count() {
                // empty inline table
                current_table = None;
            }
            continue;
        }

        if line == "}" {
            current_table = None;
            continue;
        }

        if let Some(table) = current_table.clone() {
            if lower.starts_with("note:") || lower.starts_with("note ") {
                if let Some(entity) = diagram.entity_by_name_mut(&table) {
                    entity.note = Some(extract_note(line));
                }
                continue;
            }
            let attr = parse_dbml_column(line).map_err(|m| Error::parse(line_no, m))?;
            if let Some(entity) = diagram.entity_by_name_mut(&table) {
                entity.attributes.push(attr);
            }
            continue;
        }

        if lower.starts_with("ref:") || lower.starts_with("ref ") {
            let rel = parse_dbml_ref(line).map_err(|m| Error::parse(line_no, m))?;
            diagram.ensure_entity(&rel.from_entity);
            diagram.ensure_entity(&rel.to_entity);
            diagram.relationships.push(rel);
            continue;
        }

        if lower.starts_with("enum ") || lower.starts_with("tablegroup ") {
            // Skip unsupported blocks.
            if line.contains('{') && !line.contains('}') {
                for (_, raw) in lines.by_ref() {
                    if raw.trim().starts_with('}') {
                        break;
                    }
                }
            }
            continue;
        }

        // Ignore other top-level noise rather than failing hard.
    }

    if diagram.entities.is_empty() {
        return Err(Error::parse(1, "no tables found in DBML input"));
    }

    Ok(diagram)
}

fn parse_dbml_column(line: &str) -> std::result::Result<Attribute, String> {
    // name type [pk, increment, not null, unique, note: '...']
    let line = line.trim().trim_end_matches(',').trim();
    let (head, settings) = if let Some(start) = line.find('[') {
        let end = line
            .rfind(']')
            .ok_or_else(|| format!("unclosed column settings: {line}"))?;
        (&line[..start], Some(&line[start + 1..end]))
    } else {
        (line, None)
    };

    let parts: Vec<&str> = head.split_whitespace().collect();
    if parts.len() < 2 {
        return Err(format!("column needs name and type: {line}"));
    }
    let name = unquote(parts[0]).to_string();
    let data_type = parts[1..].join(" ");

    let mut attr = Attribute::new(name, data_type);
    if let Some(settings) = settings {
        for raw_setting in split_settings(settings) {
            let s = raw_setting.trim();
            let lower = s.to_ascii_lowercase();
            if lower == "pk" || lower == "primary key" {
                attr.is_pk = true;
                attr.is_nullable = false;
            } else if lower == "unique" {
                attr.is_unique = true;
            } else if lower == "not null" {
                attr.is_nullable = false;
            } else if lower == "null" {
                attr.is_nullable = true;
            } else if lower == "increment" {
                // ignore
            } else if lower.starts_with("note:") {
                attr.note = Some(extract_note(s));
                if attr.note.as_deref() == Some("FK") {
                    attr.is_fk = true;
                    attr.note = None;
                }
            } else if lower.starts_with("ref:") {
                attr.is_fk = true;
            }
        }
    }
    Ok(attr)
}

fn parse_dbml_ref(line: &str) -> std::result::Result<Relationship, String> {
    // Ref: posts.user_id > users.id
    // Ref: a.x < b.y
    // Ref: a.x - b.y
    // Ref name: ...
    let rest = line
        .split_once(':')
        .map(|(_, r)| r.trim())
        .unwrap_or(line)
        .trim();

    let op = if rest.contains("<>") {
        "<>"
    } else if rest.contains('>') {
        ">"
    } else if rest.contains('<') {
        "<"
    } else if rest.contains('-') {
        "-"
    } else {
        return Err(format!("unsupported Ref syntax: {line}"));
    };

    let (left, right) = rest
        .split_once(op)
        .ok_or_else(|| format!("invalid Ref: {line}"))?;

    let (left_table, left_fields) = parse_table_fields(left.trim())?;
    let (right_table, right_fields) = parse_table_fields(right.trim())?;

    // Normalize so from = many/FK side when using >
    // DBML: Ref: FK_table.col > PK_table.col  means many-to-one toward PK
    let (from_entity, to_entity, from_fields, to_fields, from_card, to_card) = match op {
        ">" => (
            left_table,
            right_table,
            left_fields,
            right_fields,
            Cardinality::ZeroOrMany,
            Cardinality::One,
        ),
        "<" => (
            right_table,
            left_table,
            right_fields,
            left_fields,
            Cardinality::ZeroOrMany,
            Cardinality::One,
        ),
        "-" => (
            left_table,
            right_table,
            left_fields,
            right_fields,
            Cardinality::One,
            Cardinality::One,
        ),
        "<>" => (
            left_table,
            right_table,
            left_fields,
            right_fields,
            Cardinality::ZeroOrMany,
            Cardinality::ZeroOrMany,
        ),
        _ => unreachable!(),
    };

    let mut rel = Relationship::new(from_entity, to_entity, from_card, to_card);
    rel.id = Uuid::new_v4().to_string();
    rel.from_fields = from_fields;
    rel.to_fields = to_fields;
    Ok(rel)
}

fn parse_table_fields(s: &str) -> std::result::Result<(String, Vec<String>), String> {
    let s = s.trim();
    let (table, fields) = s
        .split_once('.')
        .ok_or_else(|| format!("expected table.column, got: {s}"))?;
    let table = unquote(table.trim()).to_string();
    let fields_str = fields.trim();
    let fields = if fields_str.starts_with('(') {
        fields_str
            .trim_matches(|c| c == '(' || c == ')')
            .split(',')
            .map(|f| unquote(f.trim()).to_string())
            .filter(|f| !f.is_empty())
            .collect()
    } else {
        vec![unquote(fields_str).to_string()]
    };
    Ok((table, fields))
}

fn dbml_ref_sides(
    rel: &Relationship,
    from_fields: &[String],
    to_fields: &[String],
) -> (String, Vec<String>, String, Vec<String>, &'static str) {
    // Emit FK-side > PK-side when the "from" end is many.
    let from_is_many = matches!(
        rel.from_cardinality,
        Cardinality::ZeroOrMany | Cardinality::OneOrMany
    );
    let to_is_many = matches!(
        rel.to_cardinality,
        Cardinality::ZeroOrMany | Cardinality::OneOrMany
    );

    if from_is_many && !to_is_many {
        (
            rel.from_entity.clone(),
            from_fields.to_vec(),
            rel.to_entity.clone(),
            to_fields.to_vec(),
            ">",
        )
    } else if to_is_many && !from_is_many {
        (
            rel.to_entity.clone(),
            to_fields.to_vec(),
            rel.from_entity.clone(),
            from_fields.to_vec(),
            ">",
        )
    } else if from_is_many && to_is_many {
        (
            rel.from_entity.clone(),
            from_fields.to_vec(),
            rel.to_entity.clone(),
            to_fields.to_vec(),
            "<>",
        )
    } else {
        (
            rel.from_entity.clone(),
            from_fields.to_vec(),
            rel.to_entity.clone(),
            to_fields.to_vec(),
            "-",
        )
    }
}

fn guess_pk_fields(diagram: &Diagram, entity_name: &str) -> Vec<String> {
    diagram
        .entity_by_name(entity_name)
        .map(|e| {
            let pks: Vec<_> = e
                .attributes
                .iter()
                .filter(|a| a.is_pk)
                .map(|a| a.name.clone())
                .collect();
            if pks.is_empty() {
                vec!["id".into()]
            } else {
                pks
            }
        })
        .unwrap_or_else(|| vec!["id".into()])
}

fn guess_fk_fields(diagram: &Diagram, entity_name: &str, ref_entity: &str) -> Vec<String> {
    if let Some(e) = diagram.entity_by_name(entity_name) {
        let fks: Vec<_> = e
            .attributes
            .iter()
            .filter(|a| a.is_fk)
            .map(|a| a.name.clone())
            .collect();
        if !fks.is_empty() {
            return fks;
        }
        // convention: {ref}_id
        let candidate = format!("{}_id", ref_entity.to_ascii_lowercase());
        if e.attributes
            .iter()
            .any(|a| a.name.eq_ignore_ascii_case(&candidate))
        {
            return vec![candidate];
        }
    }
    vec![format!("{}_id", ref_entity.to_ascii_lowercase())]
}

fn format_field_list(fields: &[String]) -> String {
    if fields.len() == 1 {
        quote_ident_if_needed(&fields[0])
    } else {
        let inner = fields
            .iter()
            .map(|f| quote_ident_if_needed(f))
            .collect::<Vec<_>>()
            .join(", ");
        format!("({inner})")
    }
}

fn map_type(ty: &str) -> String {
    // Pass through; normalize a few Mermaid-ish types to DBML-friendly ones.
    match ty.to_ascii_lowercase().as_str() {
        "string" | "str" | "text" => "varchar".into(),
        "int" | "integer" => "int".into(),
        "bool" | "boolean" => "boolean".into(),
        "float" | "double" | "decimal" | "number" => "decimal".into(),
        "date" => "date".into(),
        "datetime" | "timestamp" => "timestamp".into(),
        other => other.to_string(),
    }
}

fn quote_ident_if_needed(name: &str) -> String {
    if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
    {
        name.to_string()
    } else {
        format!("\"{name}\"")
    }
}

fn unquote(s: &str) -> &str {
    let s = s.trim();
    if (s.starts_with('"') && s.ends_with('"')) || (s.starts_with('\'') && s.ends_with('\'')) {
        &s[1..s.len() - 1]
    } else {
        s
    }
}

fn escape_note(s: &str) -> String {
    s.replace('\'', "\\'")
}

fn extract_note(line: &str) -> String {
    if let Some(rest) = line.split_once(':').map(|(_, r)| r.trim()) {
        return unquote(rest).replace("\\'", "'").to_string();
    }
    String::new()
}

fn strip_dbml_comment(line: &str) -> &str {
    // crude: // comments, but not inside quotes
    let mut in_single = false;
    let mut in_double = false;
    let bytes = line.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        let c = bytes[i] as char;
        if c == '\'' && !in_double {
            in_single = !in_single;
        } else if c == '"' && !in_single {
            in_double = !in_double;
        } else if !in_single && !in_double && c == '/' && bytes[i + 1] as char == '/' {
            return &line[..i];
        }
        i += 1;
    }
    line
}

fn split_settings(settings: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut in_quote: Option<char> = None;
    for c in settings.chars() {
        if let Some(q) = in_quote {
            cur.push(c);
            if c == q {
                in_quote = None;
            }
            continue;
        }
        match c {
            '\'' | '"' => {
                in_quote = Some(c);
                cur.push(c);
            }
            ',' => {
                if !cur.trim().is_empty() {
                    out.push(cur.trim().to_string());
                }
                cur.clear();
            }
            _ => cur.push(c),
        }
    }
    if !cur.trim().is_empty() {
        out.push(cur.trim().to_string());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mermaid::import_mermaid;
    use pretty_assertions::assert_eq;

    #[test]
    fn export_and_reimport_dbml() {
        let src = r#"
erDiagram
    PROPERTY ||--o{ RESERVATION : hosts
    PROPERTY {
        string property_code PK
        string name
    }
    RESERVATION {
        string reservation_id PK
        string property_code FK
        date arrival_date
    }
"#;
        let d = import_mermaid(src).unwrap();
        let dbml = export_dbml(&d);
        assert!(dbml.contains("Table PROPERTY"));
        assert!(dbml.contains("Ref:"));
        let d2 = import_dbml(&dbml).unwrap();
        assert_eq!(d2.entities.len(), 2);
        assert!(!d2.relationships.is_empty());
    }

    #[test]
    fn parse_basic_dbml() {
        let src = r#"
Table users {
  id int [pk]
  name varchar [not null]
}

Table posts {
  id int [pk]
  user_id int [not null]
}

Ref: posts.user_id > users.id
"#;
        let d = import_dbml(src).unwrap();
        assert_eq!(d.entities.len(), 2);
        assert_eq!(d.relationships.len(), 1);
        assert!(d.entity_by_name("users").unwrap().attributes[0].is_pk);
    }
}
